server:
  port: 8081 #端口号
spring:
  datasource: #数据源
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123@qwe
    url:  jdbc:mysql://127.0.0.1:3306/bbs?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  thymeleaf:
    mode: HTML5  # 视图模型
    cache: false # 模板缓存

  resources:
    static-locations: classpath:/META- INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/ # 静态资源路径
  messages:
    encoding: UTF-8